FROM node:14.15.0-alpine

LABEL maintainer="https://shimba.co" \
    description="shimbaco's home page."

RUN apk update && \
    apk add -t \
    build-dependencies \
    build-base \
    git \
    python

ENV PATH=./node_modules/.bin/:$PATH \
    NODE_ENV=development

WORKDIR /workspace/

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 9000
