FROM node:14.17.6-bullseye-slim

LABEL maintainer="https://shimba.co" \
    description="shimbaco's home page."

# Bashを使用する
SHELL ["/bin/bash", "-c"]

RUN apt update \
  && apt install -y --no-install-recommends \
    build-essential \
    git \
    python

ENV PATH=./node_modules/.bin/:$PATH \
  NODE_ENV=development

WORKDIR /workspace/

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 9000
